### ISSUE TITLE
Documentation generator

### ISSUE THREAD

**Issue by AnidemDex** [Totobird-Creations/Godot-Property-Descriptions#1]
Godot 3.x doesn't have (and will not have) a documentation generator as 4.x will, and there are tools there and here that tries to do it. Do you mind if I use this plugin (combined with some others like [this one](https://github.com/godot-extended-libraries/Godot-Custom-Class-Docs)) to create a documentation generator?

**Comment by Totobird-Creations** [comment]
Yes, absolutely. Go ahead.
